# Generated by Django 4.2.4 on 2023-09-01 21:46

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                (
                    "password",
                    models.CharField(max_length=128, verbose_name="password"),
                ),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="last login",
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text=(
                            "Designates that this user has "
                            "all permissions without explicitly "
                            "assigning them."
                        ),
                        verbose_name="superuser status",
                    ),
                ),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "username",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="First Name",
                    ),
                ),
                (
                    "middle_name",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Middle Name",
                    ),
                ),
                (
                    "second_name",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Second Name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128,
                        null=True,
                        region=None,
                        unique=True,
                        verbose_name="Phone",
                    ),
                ),
                ("about_me", models.TextField(verbose_name="About me")),
                (
                    "city",
                    models.CharField(
                        max_length=36,
                        null=True,
                        verbose_name="Phone",
                    ),
                ),
                (
                    "birthday",
                    models.DateField(null=True, verbose_name="Birthday"),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text=(
                            "The groups this user belongs to. "
                            "A user will get all permissions "
                            "granted to each of their groups."
                        ),
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "db_table": "users",
            },
        ),
    ]
