# Generated by Django 4.2.4 on 2023-09-18 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_subscribers"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscribers",
            options={
                "verbose_name": "subscriber",
                "verbose_name_plural": "subscribers",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="followers",
            field=models.IntegerField(default=0, verbose_name="followers"),
        ),
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.IntegerField(default=0, verbose_name="following"),
        ),
        migrations.AlterField(
            model_name="subscribers",
            name="followers",
            field=models.ManyToManyField(
                related_name="following",
                to="user.subscribers",
                verbose_name="followers",
            ),
        ),
        migrations.AlterField(
            model_name="subscribers",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
    ]
