repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: black .
        args: [--check, --config, pyproject.toml]
        language: python
        types: [python]
      - id: ruff
        name: ruff
        entry: ruff .
        args: [--config, pyproject.toml]
        language: python
        types: [python]
