version: '3'

services:
  database:
    hostname: postgres
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:${POSTGRES_PORT}
    volumes:
      - db:/var/lib/postgresql/data
    restart: always

volumes:
  db:
