FROM python:3.11.5-slim-bookworm

ENV PYTHONFAULTHANDLER=1 \
    PYTHONUNBUFFERED=1 \
    PYTHONHASHSEED=random \
    PYTHONDONTWRITEBYTECODE=1

ENV PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100

WORKDIR /app

RUN pip install poetry
COPY poetry.lock pyproject.toml ./deploy/entrypoint.sh /app/

RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi --no-root --only main

ENTRYPOINT ["/app/entrypoint.sh"]