# Generated by Django 4.2.4 on 2023-09-01 21:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                ("like", models.IntegerField()),
            ],
            options={
                "verbose_name": "Comment",
                "verbose_name_plural": "Comments",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
            ],
            options={
                "verbose_name": "Like",
                "verbose_name_plural": "Likes",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                ("Updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("Photo", "Photo"), ("Video", "Video")],
                        max_length=5,
                        verbose_name="Post Type",
                    ),
                ),
                (
                    "media",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        size=None,
                        verbose_name="Media",
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                ("like", models.IntegerField(verbose_name="Like")),
                ("comment", models.IntegerField(verbose_name="Comment")),
            ],
            options={
                "verbose_name": "Photo",
                "verbose_name_plural": "Photos",
            },
        ),
    ]
