# Generated by Django 4.2.4 on 2023-09-03 15:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models

import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date on created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="date on updated",
                    ),
                ),
                ("text", models.TextField(verbose_name="text")),
                ("like", models.IntegerField(default=0, verbose_name="likes")),
            ],
            options={
                "verbose_name": "comment",
                "verbose_name_plural": "commentars",
            },
        ),
        migrations.CreateModel(
            name="CommentLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date on created",
                    ),
                ),
            ],
            options={
                "verbose_name": "like in comment",
                "verbose_name_plural": "likes in comments",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date on created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        verbose_name="date on updated",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("Photo", "photo"), ("Video", "video")],
                        max_length=5,
                        verbose_name="type",
                    ),
                ),
                (
                    "media",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.URLField(),
                        size=None,
                        verbose_name="media",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        default="",
                        verbose_name="description",
                    ),
                ),
                ("like", models.IntegerField(default=0, verbose_name="like")),
                (
                    "comment",
                    models.IntegerField(default=0, verbose_name="comment"),
                ),
            ],
            options={
                "verbose_name": "post",
                "verbose_name_plural": "posts",
            },
        ),
        migrations.CreateModel(
            name="PostLike",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        verbose_name="identifier",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="date on created",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_likes",
                        to="post.post",
                        verbose_name="post",
                    ),
                ),
            ],
            options={
                "verbose_name": "like in post",
                "verbose_name_plural": "likes in posts",
            },
        ),
    ]
